In [1]:
import pandas as pd

if u are using dataframe , the elements are in dictionary are going as a cloumn and elements are in nested list are going to as a row

In [7]:
df = pd.DataFrame({
    'id': [101, 102, 103, 104],
    'name': ['Prasad', 'Nikhil', 'Durvesh', 'Pranav']
})
df

    id     name
0  101   Prasad
1  102   Nikhil
2  103  Durvesh
3  104   Pranav

In [5]:
df2 = pd.DataFrame([
    [101, 'Prasad', 'IT'],
    [102, 'Nikhil', 'Admin']
])
df2

     0       1      2
0  101  Prasad     IT
1  102  Nikhil  Admin

In [15]:
data = pd.read_csv(r"D:\FBS\Data Analysis\Datasets\Iris.csv")

In [16]:
data.head(5)

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [17]:
data.tail(5)

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal_Length  150 non-null    float64
 1   Sepal_Width   150 non-null    float64
 2   Petal_Length  150 non-null    float64
 3   Petal_Width   150 non-null    float64
 4   Species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [19]:
data.describe()

       Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000